### ISSUE TITLE
On top-pages.php, print the h-index for every month

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/analytics-table#7]
The h-index for a given column on top-pages.php (e.g. https://analytics.vipulnaik.com/top-pages.php?project_title=Timelines+wiki) is the largest integer *n* such that there are at least *n* pages with at least *n* pageviews.

In cases where the h-index is greater than or equal to the `limit_pagepaths` value (default 100) I'm ok printing the `limit_pagepaths` value instead of the 'true" h-index.

**Comment by riceissa** [comment]
This is done in https://github.com/riceissa/analytics-table/commit/2a4fbacb543bd9bbfa667a3226da0afcccbafaaa (it's in master so you can just pull).

I used the real data instead of what's printed, so this computes the "true" h-index.
